AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: tweet-sentiment-python
    Description: Python implementation of serverless app that publishes sentiment score metrics of tweets to CloudWatch Metrics.
    Author: James Hood
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: [twitter, tweet, sentiment]
    HomePageUrl: https://github.com/jlhood/tweet-sentiment-python
    SemanticVersion: 0.0.2
    SourceCodeUrl: https://github.com/jlhood/tweet-sentiment-python/tree/0.0.2

Parameters:
  SearchText:
    Type: String
    Description: Search text to pass to Twitter. You can experiment with the Twitter search API at https://twitter.com/search-home
    # Search text is used as a CW Logs dimension so have to keep it within the constraints of a dimension value.
    MinLength: 1
    MaxLength: 255
  LogLevel:
    Type: String
    Description: Log level for Lambda function logging, e.g., ERROR, INFO, DEBUG, etc
    Default: INFO

Resources:
  TweetSentiment:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: tweetsentiment.handler
      Runtime: python3.7
      Tracing: Active
      Timeout: 60
      Policies:
        - ComprehendBasicAccessPolicy: {}
        - CloudWatchPutMetricPolicy: {}
      Environment:
        Variables:
          LOG_LEVEL: !Ref LogLevel
          SEARCH_TEXT: !Ref SearchText

  Tweets:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/aws-serverless-twitter-event-source
        SemanticVersion: 2.0.0
      Parameters: 
        # Max number of tweets to send to the TweetProcessor lambda function on each invocation.
        BatchSize: '20' # max allowed by PutMetricData API
        # Non-URL-encoded search text poller should use when querying Twitter Search API.
        SearchText: !Sub '${SearchText} -filter:nativeretweets'
        # If true, the app will remember the last tweet found and only invoke the tweet processor function for newer tweets. If false, the app will be stateless and invoke the tweet processor function with all tweets found in each polling cycle.
        StreamModeEnabled: 'true'
        # Name of lambda function that should be invoked to process tweets. Note, this must be a function name and not a function ARN.
        TweetProcessorFunctionName: !Ref TweetSentiment